apiVersion: v2
name: tailscale-derp
description: Run a custom tailscale derp server on Kubernetes.
type: application
version: 0.17.0
appVersion: "v1.98.3-a98bcf5"
sources:
  - "https://github.com/coreweave/tailscale-derp"
