apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tailscale-derp.fullname" . }}
  labels:
    {{- include "tailscale-derp.labels" . | nindent 4 }}
  annotations:
    {{- tpl (toYaml .Values.deploymentAnnotations) .  | nindent 4 }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tailscale-derp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- tpl (toYaml .Values.podAnnotations) .  | nindent 8 }}
      labels:
        {{- include "tailscale-derp.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tailscale-derp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          env:
            {{- tpl (toYaml .Values.env) . | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- range .Values.service.ports }}
            - name: {{ .name }}
              containerPort: {{ .targetPort }}
              protocol: {{ .protocol | default "TCP" }}
            {{- end }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            {{- tpl (toYaml .Values.volumeMounts) .  | nindent 12 }}
        {{- range .Values.env }}
        {{- if and (eq .name "DERP_VERIFY_CLIENTS") (eq .value "true") }}
        - name: {{ $.Chart.Name }}-tailscaled
          securityContext:
            {{- toYaml ($.Values).tailscaled.securityContext | nindent 12 }}
          env:
            {{- tpl (toYaml ($.Values).tailscaled.env) . | nindent 12 }}
          image: "{{ $.Values.image.repository }}:{{ $.Values.image.tag | default $.Chart.AppVersion }}"
          command: ["/usr/local/bin/containerboot"]
          imagePullPolicy: {{ $.Values.image.pullPolicy }}
          livenessProbe:
            {{- toYaml $.Values.tailscaled.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml $.Values.tailscaled.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml $.Values.tailscaled.resources | nindent 12 }}
          volumeMounts:
            {{- tpl (toYaml $.Values.tailscaled.volumeMounts) .  | nindent 12 }}
        {{- end }}
        {{- end }}
      volumes:
        {{- tpl (toYaml .Values.volumes) .  | nindent 8 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
