{{- range .Values.calicoNetworkPolicy }}
---
apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations: {{ .annotations | toYaml | nindent 4 }}
  labels: {{ .labels | toYaml | nindent 4 }}
spec:
  {{- if .selector }}
  selector: {{ .selector }}
  {{- end }}
  {{- if .egress }}
  egress: {{ .egress | toYaml | nindent 4 }}
  {{- end }}
  {{- if .ingress }}
  ingress: {{ .ingress | toYaml | nindent 4 }}
  {{- end }}
  order: {{ default 200 .order }}
  types:
  {{- if .egress }}
  - Egress
  {{- end }}
  {{- if .ingress }}
    - Ingress
  {{- end }}
{{- end }}

{{- range .Values.kubernetesNetworkPolicy }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  annotations: {{ .annotations | toYaml | nindent 4 }}
  labels: {{ .labels | toYaml | nindent 4 }}
spec:
  {{- if .podSelector }}
  podSelector: {{ .podSelector }}
  {{- end }}
  {{- if .egress }}
  egress: {{ .egress | toYaml | nindent 4 }}
  {{- end }}
  {{- if .ingress }}
  ingress: {{ .ingress | toYaml | nindent 4 }}
  {{- end }}
  {{- if .policyTypes }}
  policyTypes: {{ .policyTypes | toYaml | nindent 4 }}
  {{- end }}
{{- end }}
