---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Charts: Publish to GHCR OCI"

on:
  release:
    types: ["published", "created"]
  workflow_dispatch: {}
  workflow_call: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  publish-charts:
    name: Publish chart
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Helm
        uses: azure/setup-helm@1a275c3b69536ee54be43f2070a358922e12c8d4 # v4

      - name: Package & Push Helm Charts
        shell: bash
        run: |
          helm package chart/tailscale-derp --dependency-update
          pkg=$(ls tailscale-derp-*.tgz)
          helm push "${pkg}" oci://ghcr.io/${{ github.repository }}/chart
