---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Mirror to Gitlab

on: [push]

jobs:
  mirror:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: yesolutions/mirror-action@v0.7.0
        with:
          REMOTE: 'https://gitlab.com/${{ github.repository }}'
          GIT_USERNAME: ${{ secrets.ORG_GITLAB_SYNC_UN }}
          GIT_PASSWORD: ${{ secrets.ORG_GITLAB_SYNC_PW }}
