---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Container: Image Build"
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "Docker/**/*"

env:
  # renovate: depName=tailscale.com datasource=go
  UPSTREAM_TS_VERSION: v1.68.0

jobs:
  publish-images:
    name: Publish Image
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Log into registry ghcr.io
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6.2.0
        with:
          push: true
          context: ./
          file: ./Docker/Dockerfile
          build-args: |
            VERSION=${{ env.UPSTREAM_TS_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.UPSTREAM_TS_VERSION }}
            ghcr.io/${{ github.repository }}:latest
