name: "Container: Image Build"
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
    paths:
      - "Docker/**/*"

env:
  UPSTREAM_TS_VERSION: v1.68.0

jobs:
  publish-images:
    name: Publish Image
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb

      - name: Log into registry ghcr.io
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        with:
          push: true
          context: ./
          file: ./Docker/Dockerfile
          build-args: |
            # renovate: depName=tailscale.com datasource=go
            VERSION=${{ env.UPSTREAM_TS_VERSION }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.UPSTREAM_TS_VERSION }}
