---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Release"

on:
  workflow_dispatch: {}
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    permissions:
      contents: write
      packages: write
      pull-requests: write
      actions: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          fetch-depth: 0

      - name: release
        uses: googleapis/release-please-action@a02a34c4d625f9be7cb89156071d8567266a2445 # v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

      - name: Dispatch Helm Action
        if: ${{ contains(steps.release.outputs.paths_released, 'chart/tailscale-derp') }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh workflow run charts-publish-oci.yaml

      - name: Create Release
        if: ${{ steps.release.outputs.prs_created == 'true' }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR=$(echo '${{ steps.release.outputs.pr }}' | jq -r .number)
          gh pr merge --squash --auto $PR
          gh workflow run release.yaml
