---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "Release"

on:
  workflow_dispatch: {}
  push:
    branches: [main]

jobs:
  release:
    name: Release
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-22.04
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: release
        uses: googleapis/release-please-action@v4
        id: release
        with:
          config-file: .github/release-please-config.json
          manifest-file: .github/.release-please-manifest.json

  publish-helm:
    name: Publish Helm OCI
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    uses: coreweave/tailscale-derp/.github/workflows/charts-publish-oci.yaml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write
